# Calculate Spanning Trees of a Complete Graph

In [1]:
from sympy import symbols, Matrix, det, zeros
import numpy as np

In [2]:
def tree2matrix(tree, n):
    """
    Convert a tree to a matrix.

    input:
        tree: the string of a tree from part of the cofactor of the Laplacian determinant
        n: number of vertices

    output:
        m: the adjacency matrix of the tree
    """
    m = np.zeros((n, n))
    for i in range(n-1):
        m[int(tree[4*i+1])-1, int(tree[4*i+2])-1] = 1

    return m

In [3]:
def get_lap(n):
    """
    Get the Laplacian matrix of a complete graph with n vertices.

    input:
        n: number of vertices
    
    output:
        A: the Laplacian matrix, variables are indeterminates
    """
    A = Matrix(zeros(n))
    for i in range(n):
        x = symbols('x{}{}:{}{}'.format(i+1,1,i+1,n+1))
        for j in range(n):
            if j != i:
                A[i,j] = -x[j]
        A[i,i] = sum(x) - x[i]

    return A

In [4]:
# get trees from cofactor of Laplacian determinant
n=6

A = get_lap(n)

trees = []
l = list(range(n))

for i in range(n):
    l_i = [j for j in l if j != i]
    B = A.row(l_i)
    C = B.col(l_i)
    tmp = str(det(C))
    for j in range(n**(n-2)):
        trees.append(tmp[(4*(n-1)+2)*j:(4*(n-1)+2)*j+4*(n-1)-1])

KeyboardInterrupt: 

In [ ]:
tree_adj = np.zeros((n**(n-1), n, n)) # adjacency matrix of all rooted spanning trees of K_n
for i in range(n**(n-1)):
    tree_adj[i,:,:] = tree2matrix(trees[i], n)

In [ ]:
for i in range(n**(n-1)):
    print(i)
    print(tree_adj[i,:,:])
    print('\n')

0
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


1
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


2
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


3
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]


4
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


5
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


6
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


7
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]


8
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]


9
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]]


10
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 

### Get the adjacency matrix of tree graph of $K_n$

In [ ]:
tree_graph = np.zeros((n**(n-1), n**(n-1))) # adjacency matrix of tree graph of K_n

for i in range(n):
    for j in range(n**(n-2)):
        tree1 = tree_adj[i*n**(n-2)+j,:,:]
        for k in range(n):
            if k != i:
                tree2 = tree1.copy() 
                tree2[i,k] = 1
                tree2[k,:] = 0
                indice = np.argwhere([np.array_equal(tree2, tree_adj[l,:,:]) for l in np.arange(k*n**(n-2),(k+1)*n**(n-2))])
                tree_graph[i*n**(n-2)+j, k*n**(n-2)+int(indice)]=1

In [ ]:
print(tree_graph)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


### Calculate Jordan Form of the Tree Graph

In [7]:
def num_of_jordan_block(matrix, c, k):
    """
    Get the number of Jordan blocks of a given eigenvalue.

    input:
        matrix: the adjacency matrix of a graph
        c: the eigenvalue
        k: size of the Jordan block

    output:
        num: the number of Jordan blocks of eigenvalue c with size k
    """
    m = c * np.eye(matrix.shape[0]) - matrix
    if k == 1:
        return matrix.shape[0] + np.linalg.matrix_rank(np.linalg.matrix_power(m,2)) - 2*np.linalg.matrix_rank(m)
    else:
        return np.linalg.matrix_rank(np.linalg.matrix_power(m,k+1)) - 2*np.linalg.matrix_rank(np.linalg.matrix_power(m,k)) + np.linalg.matrix_rank(np.linalg.matrix_power(m,k-1))

In [8]:
num_of_jordan_block(tree_graph, -1,1)

1

In [2]:
n=3
with np.load('tree_adj_and_tree_graph_{}.npz'.format(n), allow_pickle=True) as data:
    tree_adj = data['tree_adj']
    tree_graph = data['tree_graph']

In [3]:
tree_graph

array([[0., 0., 0., 1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 0.]])

In [4]:
test = [[0,1,0,0,0,0,0,0,1],[1,0,1,0,0,0,0,0,0],[0,1,0,1,0,0,0,0,0],[0,0,1,0,1,0,0,0,0],[0,0,0,1,0,1,0,0,0],[0,0,0,0,1,0,1,0,0],[0,0,0,0,0,1,0,1,0],[0,0,0,0,0,0,1,0,1],[1,0,0,0,0,0,0,1,0]]

In [5]:
eigv, eigvec = np.linalg.eig(test)

In [4]:
T = 2 * np.eye(n**(n-1)) - tree_graph